// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Reply.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ClientVideoStream.Handlers {

  /// <summary>Holder for reflection information generated from Reply.proto</summary>
  public static partial class ReplyReflection {

    #region Descriptor
    /// <summary>File descriptor for Reply.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReplyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtSZXBseS5wcm90bxIaQ2xpZW50VmlkZW9TdHJlYW0uSGFuZGxlcnMixgIK",
            "BVJlcGx5EjgKBmhlYWRlchgBIAEoDjIoLkNsaWVudFZpZGVvU3RyZWFtLkhh",
            "bmRsZXJzLlJlcGx5LkhlYWRlchI4CgZzdGF0dXMYAiABKA4yKC5DbGllbnRW",
            "aWRlb1N0cmVhbS5IYW5kbGVycy5SZXBseS5TdGF0dXMSEwoLZGVzY3JpcHRp",
            "b24YAyABKAkifwoGSGVhZGVyEhEKDVVOS05PV05fSEVBRVIQABIYChRFU1RB",
            "QkxJU0hfQ09OTkVDVElPThABEhAKDFNUQVJUX1NUUkVBTRACEg8KC1NUT1Bf",
            "U1RSRUFNEAMSEgoOU1RBUlRfVFJBQ0tJTkcQBBIRCg1TVE9QX1RSQUNLSU5H",
            "EAUiMwoGU3RhdHVzEhIKDlVOS05PV05fU1RBVFVTEAASCwoHU1VDQ0VTUxAB",
            "EggKBEZBSUwQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientVideoStream.Handlers.Reply), global::ClientVideoStream.Handlers.Reply.Parser, new[]{ "Header", "Status", "Description" }, null, new[]{ typeof(global::ClientVideoStream.Handlers.Reply.Types.Header), typeof(global::ClientVideoStream.Handlers.Reply.Types.Status) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Reply : pb::IMessage<Reply> {
    private static readonly pb::MessageParser<Reply> _parser = new pb::MessageParser<Reply>(() => new Reply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Reply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientVideoStream.Handlers.ReplyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Reply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Reply(Reply other) : this() {
      header_ = other.header_;
      status_ = other.status_;
      description_ = other.description_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Reply Clone() {
      return new Reply(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::ClientVideoStream.Handlers.Reply.Types.Header header_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ClientVideoStream.Handlers.Reply.Types.Header Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::ClientVideoStream.Handlers.Reply.Types.Status status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ClientVideoStream.Handlers.Reply.Types.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 3;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Reply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Reply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Header != other.Header) return false;
      if (Status != other.Status) return false;
      if (Description != other.Description) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Header != 0) hash ^= Header.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Header != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Header);
      }
      if (Status != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Header != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Header);
      }
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Reply other) {
      if (other == null) {
        return;
      }
      if (other.Header != 0) {
        Header = other.Header;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Header = (global::ClientVideoStream.Handlers.Reply.Types.Header) input.ReadEnum();
            break;
          }
          case 16: {
            Status = (global::ClientVideoStream.Handlers.Reply.Types.Status) input.ReadEnum();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Reply message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Header {
        [pbr::OriginalName("UNKNOWN_HEAER")] UnknownHeaer = 0,
        [pbr::OriginalName("ESTABLISH_CONNECTION")] EstablishConnection = 1,
        [pbr::OriginalName("START_STREAM")] StartStream = 2,
        [pbr::OriginalName("STOP_STREAM")] StopStream = 3,
        [pbr::OriginalName("START_TRACKING")] StartTracking = 4,
        [pbr::OriginalName("STOP_TRACKING")] StopTracking = 5,
      }

      public enum Status {
        [pbr::OriginalName("UNKNOWN_STATUS")] UnknownStatus = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("FAIL")] Fail = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
